<?php
$ch="ViewsBackend/dashboard.php";
if(isset($_GET["ch"])){
    $ch=$_GET["ch"];
    $vue="ViewsBackend";
    if($ch=="DASHBOARD"){
        $ch="$vue/dashboard.php";
    }elseif($ch=="PRODUITS"){
        $ch="$vue/produit.php";
    }elseif($ch=="COMMANDES"){
        $ch="$vue/commande.php";
    }elseif($ch=="UTILISATEURS"){
        $ch="$vue/utilisateurs.php";
    }elseif($ch=="LIVREUR"){
        $ch="$vue/livreurs.php";
    }elseif($ch=="CHOIX"){
         $ch="$vue/choix.php";
    }elseif($ch=="STOCKS"){
        $ch="$vue/stock.php";
    }elseif($ch=="FORMULAIRE_CREATION_PRODUIT"){
           $ch="$vue/formulaireCreationProduit.php";
    }elseif($ch="FORMULAIRE_CREATION_USER"){
        $ch="$vue/formulaire-connex.php";
    }else {
       $ch="$vue/DASHBOARD.php";
    }
}

?>